/**
 * 当一个字符串满足如下条件时，我们称它是 美丽的 ：

所有 5 个英文元音字母（'a' ，'e' ，'i' ，'o' ，'u'）都必须 至少 出现一次。
这些元音字母的顺序都必须按照 字典序 升序排布（也就是说所有的 'a' 都在 'e' 前面，所有的 'e' 都在 'i' 前面，以此类推）
比方说，字符串 "aeiou" 和 "aaaaaaeiiiioou" 都是 美丽的 ，但是 "uaeio" ，"aeoiu" 和 "aaaeeeooo" 不是美丽的 。

给你一个只包含英文元音字母的字符串 word ，请你返回 word 中 最长美丽子字符串的长度 。如果不存在这样的子字符串，请返回 0 。

子字符串 是字符串中一个连续的字符序列。
 */

function longestBeautifulSubstring(word: string): number {
  let isFind = ''
  let currentLength = 0
  let res = 0
  for(let i=0,length = word.length;i<length;i++){
    const char = word[i]
    // 功德圆满
    if(currentLength && char !== 'u' && isFind === 'u'){
      res = Math.max(res, currentLength)
      currentLength = 0
      isFind = ''
    }
    if(char === 'a'){
      if(isFind === ''){
        currentLength ++
        isFind = 'a'
      }else if(isFind === 'a'){
        currentLength ++
      }else{
        currentLength = 1
        isFind = 'a'
      }
    }else if(char === 'e'){
      if(isFind === 'a'){
        isFind = 'e'
        currentLength ++
      }else if(isFind === 'e'){
        currentLength ++
      }else{
        currentLength = 0
        isFind = ''
      }
    }else if(char === 'i'){
      if(isFind === 'e'){
        isFind = 'i'
        currentLength ++
      }else if(isFind === 'i'){
        currentLength ++
      }else{
        currentLength = 0
        isFind = ''
      }
    }else if(char === 'o'){
      if(isFind === 'i'){
        isFind = 'o'
        currentLength ++
      }else if(isFind === 'o'){
        currentLength ++
      }else{
        currentLength = 0
        isFind = ''
      }
    }else if(char === 'u'){
      if(isFind === 'o'){
        isFind = 'u'
        currentLength ++
      }else if(isFind === 'u'){
        currentLength ++
      }else{
        currentLength = 0
        isFind = ''
      }
    }
  }
  // 功德圆满
  if(currentLength && isFind === 'u'){
    res = Math.max(res, currentLength)
  }
  return res
};

console.log(longestBeautifulSubstring("eieuuoeeueauueeoiiueaeuioeiiieioaouoeeoiiauiueiiuieueeeoaeaeoooiuauiaaueieoeeeeioauaouueiioeiaaaaooeaaaeoouoaoioauoaeuiioaiuuiaaaiieiuiuoiaeuuiooeiiuoaauoioeaeieaeeeiouieuaaaaaeoaeiaeeeaoaeooueieaaaeieooouueaueeiaiuoioiioieuoeeoeaaeeaauoaiaoaauaauioaueiaiooeoiiaiauaooiiauaiaoaoeaioeiaeeuueioauoueuaaiiouoeoeoiaeeooaauieoeaiueioiaieouiaeauaeiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuiuaeouiioieouieeiuaeeuoiooioiiaoueioeuaeeoaauoaaeeaaoiuueoeaeoaaeueoueeiiiuiouieaiuoieeoooueiiiaeeuaaieeaaoiuuoeuoauouiieuaeeiueaeeeaaoieaeuiuoeuoaaiueieiouiiiaoueuuiuooeioaeooaeueouiaeuaaiueuoeeiouioiiueiueaaiuoaieuiaoeuoeaeaiuaaoeeuouiiioeeoueuuauoieiaoaeeaeioouoaiieueoauaoeeoeouaiaoaueioiuaooouiueuieuauieeoeaiouoaoeeeueuoeuieooaaaaaiuoououiuuueoioieueuueaueaeuaieueeaieioieuuuueoooueueoiaoiuuiooiauaaiiiiuoaaueeaiiaeaauaooooeaaeuiaaouooauaaaaiieiaeeeeeiauiiuaueieuieaoeeiauiuaueouaeoaaoiuaoiaiouaiaeoiaooieeioiieieioeeioeuioeiooouiiioaiaeeaaieouoaooaiaiueeuieoiuaeuieeiuaoaueiouoieauieiuoooieuiaooeaeaoiueaeeuieaioiuoaeieuaaeouuoiieioeoiaeuiiiuiuaaaoeaaaoiuauaiiuaaaaiieeueeoieuiueuaueiiaioaoaoueiieueoauuueeeeuuueoiuuaiaaeuauuiaeuuaeiaiiioiooeaeiaeoeaeouuaouueeiieaoaeoaueuaoouoioeiaiuiouaueuaiaoeouoeoooioiuioaeeoeaaoioeiioiuoaiiuioiiioeuiiaaaieaoaaeoaeieuiiiuieiieaaioaueoiiiuueeiouuueoiiaeuuaeaaiauaeeieoaioiiuueuaoieieiuiaioeaeuiiaioaieeeaoaieoooiuiaeuuuieeaeeeeuoeueioeiiaaieaiaiiieiouueaouoooueeoiauooeieeoeuoueioauieoeuooiiaiueeouiiuuiaiuuouoaaiuiiiouuuaiiiuiiuouiioaoauiaoeiioaooeuoaauaiiieiuueuueioeaioaaieuuoioeaeeeuauouuiaauuiauuuaiiiooaiaeaeeuioaueeaoiaioiieooueaieoeieoiaouuuuioaieauioeuoauauaaeaoueeiaaoooauoioueaieeaaiuuiieieaaaeoiueeoeoeoaaoioaueeoeoiooeiioiaoeieieaeiaaaoeeuoiueaueoeoaueeiioauuuoaiaeaooaiaaauuieaioeaaoeioouaiauiaaoieiiieeioeeuaiauuaeeooiuuuaeeieaeieoaaiioaoooeaaeaooouaaoeaoiiuaiauooaiuoeauoeiaeaaeueeiaiooaeaoioeuuauaioaiiioioeuuueiuaeoeaiiuaioiueooioeiueaaeueeiauoiaoeooiuaeuoaououiiiauuaaeeuaiuueaaoioueouaooaaiieeeiueieeouoieiuoueeueauauoueaooaoiuouuiauaeoiouaoeaauaaaoaaueoaeaoeuaiiiaueeiiaaoeuaouiaaiauoeeueueiaooeiooaeuooiieioaaeiueuieuoueiaeiiiaaueaaaoauiauaooaeoeouaaoeeoieuioeuooeaeeoioeeoouieiouuooeaioooouoaoeeouueioaeuoeoiioeouoeuiuuaaouaiuaioaiiuiiuuieaoiiieaaeeioeeiuuouioiuoaiuuuouoeauuoauoeiuuoiiuauoaeuieaiaaoaoiieoeeiaoaueuuoiaauioueeiueeaouioiiauoeuaooiueaaeuuiiiooioeiuioaeuuaouieeiuooaeeaeiiiaiieoaeeoaoioieiuiaeiaiiiouoeoeaeuiuaoeuiiouoaeioiouioiaouiaoooioooieiieaeeaiaaiuoaaaaeoauioiouaaaoeiiueaooeieieueaoiuiaiueaaauiuiuooeaaaaeoiooeueiaaueeaeaoouoioouoeouaoaooauieeuuoeooaauuoaueoaaauiiueoaauiiaaiaoaiuoeeooiiauaueeuoiuooaiueeeauaoeeaiieeoeaaaoueaeiouaouioauoouaeoiauaauouuuaoeuaaeueeeouoaouueaooiueeauuiiioeaeeieoaoeaooauaiiiueoaiauoueeiooueeiooiaouauiaoooioaaaaoeiaieoeaeaeeoaoaeeaeeuuuuioouaioeouuiuouuoeoaeeaaaeeaoooiaeieiuiuauouuieuiauooioiuoeeoieooeeouoiaaoueoaaiaiuauaauouiauiuoiioiiiauiuooiaooeeiuoeaoaeouuauueiueiuoioeiiaiioueeuiiiueoaieuueaoaiioeeuuauuuiuaueooeaaeeioieuieuuieaeoeoaaoeaoaoueiiaueuouiuuaauiiiuuoaaouaeioioooieoaioeouiiuoeaiaiiueoauaaiaeaaeouaeoiouieuaiaeuieuuioueiueueuaooiiouaioeuooeuaaoooieuauuaueiieoeiouaoaeuiaoaooeoeiaoieeaiiuaeaeauoaieeoeoeoauiauiaooouioaoiueuiueaueaaaoaouoeauueaieeuaiueiuauiueaoieoaioouiaaeuiiiueuaiuaiaeiaouooeioaoeaoiaieaeiuouaieeieoaiaaoioaeau")); // 2169
console.log(longestBeautifulSubstring('auoeioueiaaioeuieuoaieuaoeuoaiaoueioiaeuiuaeouaoie')); // 0
console.log(longestBeautifulSubstring('aeiaaioaaaaeiiiiouuuooaauuaeiu')); // 13
console.log(longestBeautifulSubstring('aeeeiiiioooauuuaeiou')); // 5
console.log(longestBeautifulSubstring('a')); // 0
console.log(longestBeautifulSubstring('oaiueoeoieeeeaoiuaoaeoiouaueaiooeuaeuouaiiauoooeaouuooauiaiauiaaeeaeuiaeoaiieoiauueoouuueeaeeeiiiouooiiiaoaoiiaaiuoeouiauooieaeaaieeouoiuieieooaiuoeuiueiuueeuaaoaueioououuioaeueauauiaueuaeaeoaaooiiueeiieieeouueoieaaoaiaeuuiiooeuuoeoaaioeiaioaouiaaaaaaueoeeoiauaeuiuieiuoaauaeauaeoieiaieiuioeoiuiooieiueuoaauooioueeuiuoeoouiieeoaoueouoouoiuuauieaaoooueaiuoeeeuoiueiaaioeaoeaaaoauaioaoioioaeueaaoioaooaooiiaeiaeuuaouoaouaoeiaueuueieuuauuauuouioiiaaaieiauuieaoooaoieuoioiaaeiaueeieeoaaeuaeoaeiuioiuuaaiauauiiioaueoeuiaooieooiouiuaaoueouaeauuuaeieieaioiauaooiioiueuieoiuiouoiiuoeiieeaeaaiuauuueuiuieaieiaieooeueeouueaeaaoieeauiieooaieioeiioeuaooeeeiiaieiiiaeiuueioiuuuaiaaaeueuieaaoiooaueuiuaiaaiaiooaoeeaaaoiaeauuoioieaoieooueueeuoiiaoiaaaouueaieuououiooouaaouiaaeaeoiuiieaeoiauaeueiiooiuiaiuieaaiooaaeeeauoeoieoooeuuooaaeuieuaouaiueaoaooeiiaouiiiaaeeueeoeoeaoeuaeiiueeoueaoiuieooaioaaieoouaeaaeoaeuaeieoeioouioiiiuiauioeeeueieieueeioeiieuaeeuoeuouiuaeaaoouaiioaaooeeeaeoauouueeeeaiiaiaeaoioaaueeuaoouooieaeieeiaaaeeioaoeaiouaaaiaeaeiooaeiaiuuaeaaeeiiouieauaioeeaaouieoaiouoeauaaaeieauoeoiiauaaooauooeoieaoaiioueuoaoaaooueeeuiieoeoiuiaioooaaaueeaoooieieeaieoiauiauoouuaoeueeioeauoaoiieeueeaieuuaououaoeuieiuueaoeieaaaoaauoiaoauuuoaieoauieuioiuaeeeeuuiooioieoeueiuuuaiuouuouooaooaaiiuueioiuoeuauaoeiaooeaaeooieeueeeeuoiueaeaeoiiuieeaaauiieieaiaooeieiaoooueieeuiiaoiuuoueuueaaauauooieuuaoaueuuuaieaieoeaeeaoeaueiuooaeauuiueeoaeieioeeiuiuuooieaiaueoioeuoiaiauiiuoaeoeiuueaiooooiuuuaoiaoaiouuoeoeeaauieaeouuaiaiioeauoioeououuoiioiaooeoeeoioieuuaaeaooeaeiuoiaaaoouaaeaaoiauueuoiieeaaueiiaueeiiuaeooeiueuoaioiaeaaoeeoeauaeiaaiuiaeiiiuoeoaieeuuiaaueaaeaoauoeueooeeuaioaeeouauuiioauiiuoiiiiioioaiuoaiueoouaaoeoeouaaeeieiaiaiiaeiiauieeueaaaeiieuaeiiuioaouaauaiaaiuauuoiioiiiiieoiooaoaoiuaeooiiiuuauuiueieiueeaiiuaaeoeaoaoeoaaeieoieueoieouoiauieaoiiiieooioeeeueeoooeouaoeiuiaaaaueiuuuieieeeoiiooaiuoeaueuioaeeoiiuoiiaaoaueuuiaieuoaoaaauouoaieaooooeiieuuuuiiueauaeaaoaeiuououuuiuueoiaiiuoioeeaueoaioeuoaooeoeooueaiiuuuiaiiuoauuaoeeeieoiiueauaoeaoaeioeoaiaeoueuaaiuaoioeiuaiieeaiiuaaiaiiaoouuaiiueoiuiuaiuueueiuieeiaeooieioieueeeioaeuooiieaoaoaaeeoaiaueuaeaoaaeeeoaiouaeeaauuooieuaoeeeaeaueueuieeeueeiaaeoaouueaiioeauioeoiioiaueioeeeaeeueouaiuaiaeeeuuauiiuuaiooauuaaouoieuouiueueoauuioaoouiuuaaiuiiieaiaoaoouauiauuoueeaiieeeiuoooeuoaauioiieooueiaueaoaouueuoooeaioieaoeiiiaieaoieeaeuiouiiuaiaaaaaaaeooeoueoaoaeiuuauouiaauoaiauuaeaaiiiaeieeooiueuuieeiiiauoiauoeaeuieaaieuuoeoooeaioauoiaaieuuioaeeouoeuueououaauoaaeoiuieoeaiiuueiuiaoieoioiuieooaueieiauieiaauuuiouieaoieoeoouiiaieauaeaoeuaieeiuaauoeeaaoiaauoaieiuouuuoaaeuiioiauueaoeeaeaeoaouieouuoeoeioeaeioaiuoouueiauuaeaeaiuoeaoouoiouaaoaeeuoiieeeiaooeeeouoiiueauoeiueuuaueuieouaouaeiueoiiieeoauoooeaoiaaooiauoioeouuuuuuaaiiioaueaoooaauuiuooaiooaoeaioiuaouuaeooiaiouiuoeiiuiaiiuoooeuuuaeaieeiuiiaeeeaoeueiaauoaiiiooeiaeoaieieueaiooueoueeoaioaouiaaauaoeaioeiaoaiaooiiuooeuaiuaoaouiuoueieeaiooeuaioeiauaioaeoiiuaauaeioouaooioooaeeaueaeoueeaeeiouaeaiauioouueoeueuaauuoaeaaaeiiauueiueieuooaioooaaeueiaiiuiuaieiuaioauaeauuaiioueioaeuooeoeoiueueeuiiooouiauuueeeaaeaeuouiueiueiaaieeaauoaeaeoeueuoeoiuiuuiuueuaioiaaeiioiuooeioieaoioouuaouoaiaeoeiuueauooaaoooeeuuuioeiaouueioeieoauaiauaaeoaiiieauaeioouoiuueiiuaioaeooiooeueueiouuoiaoooioeeeueiaoauiiooeuouiiooaiiiieioueoooioaoueeuaeeiuoeeouaaeauioeuieiaieeiaoueeeaeouauuiaiiauiauiiaooeoaooiuoioiieeaauiaeaioaaeuaeaiueeueeeeiueeaiuiiuoeeueoiuiaieaaiauoiuooeuiuiieiuaooeoaaooaeouoeuooiaauaauiiieiuiuiaaueuuiuuouioiaoeuaeueeieoieeooeouauoaeeueioeiaeaaooieoioooeaiiooiaeeaooaeuaouaiaiaoiuiouiaieaiaaoeeuioaieueoeeiaaoeauioeuiuaouoauooueoiaoeueaaiooouiouoaaiuoeuiiueuaiouoeauuiueaiiaieaoiaaeuuouoeioeiuaaooiiiieuauoiaooaauaouuieiueioueaioaooauiueeueuuooaoeeoaaeeeiuoueeeouueiuaaeeoaiouiiaaiouaeeuioaoiueaaeaeieueaoeiiaauaeeoeuouoaeiiioaiuuueueoaauoeueoeaaaaiaaiiuoaiaeieuuooiooouoiauooeieiiuuooieoaiauieeaiiueuoaaioauuuiieeaaioeiuoauiiiiuaaueoaiiaiaauieaeueooouiaaiouueiioeiueuouaiaauieuaiouiuaeeeauaeieeuoaeaaaoiaaaiaeauaioaaeiauoaiioieeeieeuueuououaiieaiuuauaeuauaaeoeuioaoaieiuieuuuoiuioeaoiauoaueiaeeaoooueoieeuaauaoaieoaueoioeeeuiiuueaauoaiaaoeaauaooeuuauioeaoiaauaiiaoioeoiuuiieiuieeaieiiouaioeaieeiaiuoieooaiaueauoaaiaeueueooooeaoioiooaiuiueauieieeuieaeoaoiieieuuiaaieoeuaouueauiiiouoeoueoaauaiuuieaaaoououaeaiiauiouiauiioaooeueoiiouiaiiouoiiiieoiiaauiueeuuiiuiuaaaaeeeuoaiaiiaeiuauoauaaaeeeaieieuaeaaeeiiueioaeaeeaueaaaioeaeaooeoaeiuaoeuaieaaiuaaueeoooieeooaieuaiiiuiaiaiiueiaoaiiiuaeeaiiaaeuoaeaiiiiaaouaaouaaiiiuueeoaouueuieoaaaiieeooaoooaoouoauuauiaaeuouaaiuuioooiouaiauuoeaeoaiaeouuoeiaouueiieiaueuieouaauaoaoeooeoooaeouaaiaueauioeuaoeeoaooiaeaooioaueooaaeouuueoiueeiioaueuoioioiiuoaoeeuaeioaooiaiuouioaeuoueeeeuuaueoiueoaaiuioiauueoueaiooauiuaioueeoaaoaoooiaioeuoaauoaiuooaeuieuiiieuueieiiuuoueeoeuuoieoaaoaeioaieuuuoiieouiueeouaeioaieeooaueeeeeeuaieuiuiiuiiiuouoooueeuaeueoaooauieaueaeoiaaoeaoaoiauaoioaaeoiuiauoiaaaoeaeieeuiaueueiuouuuaiaaeiaoiueaoeiuooiauoeauueaaeeieuoiooaieiaeeeeouiiioiieoeeuueeioeueeeeoaiioaieuioeuuiioieaooieiieiiieaooeuiaaeuaauuueououooeauiaiuaeiaeueiaoeiaeeuoooououoeoeouiiouoouieoiaoaeiiuoieueouuiioouauaoiaioauuioooaeauiaaoaoaoiiauuuaiueaioaouauouoauioeuiauoeoauuiouooauaeieoioaioieueuoeaaauoueuoeeioiiaeeuiauoiouueeooeoaauaooeaoauaeeioiaiuoeouieiuaeieaieuooioeoouuooeauaoiooeeeiaiueeaeueiuuieioaeoeiaoaaiuaoiauaiueeoaoeeiiaiauioeoaeaoaeiaoeaoioeoeieaauioaeuoeaieaiaeueaoieeeouaueoeoouiuoaouuaoaaaoiueooaoieeoaaueeueouiuoouuoueieioiaeaaaeieauioaoeaoaiieeiooieioeaaoiuoaaaiuoooouaeaueeeooeeoeaaioaaeaeoeuuiuuoiaieoeaeaiaieaeauooeueueioioioooiiuaouauuieoueieuoueooeuauuueuuuoaaiaauieuoeuaoaaaoaooaoaouoeiueeuuoauiaeaueaaeiaiaoieiaiauaioooeaeoeeueiiaieeieuoiaeaeoiaoeaeieeaeuuieoeaoaeeuiaoueieiiaoeieuuooaouuooaoaaoaeeoeauiiuuuueoeoaouioaaiaaioaaaaeioiaaaiiieaeiioiuuuauauieiooiieeuuuaoioiaueeoaiueoeiueeiauueoioooiuieiaoeiuoueuaiooueeeuioiiuioiuaeeaoeuieoueouuaeiieiiueaaaiauueeeieieiouaiueuoaaiiuooaoaoaouuuiuieioiaeauaooieuaaeeiieiieaooaiiuueeuaueiieaeoeooioeeoaooeueuaaaueooueeaueuueaueoouuiooouieiaeeuuuuoiuiiaaiiouoiuieuaueaueiiuoeueeiuiaauioiuieiaoaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuueouiaoueiioouueuoiiieeeeiouiauoiaieeiauoeouaeoaueaoeuuoeoeoaoeioaueioaaoueuuioaeeeooauoieuoiuooieiaoaauuaieieueioeiioaeaouiieoaiuiooauuuueeouuoooiauiioeouaeoueiuoiieiauioauuoeaeoeeaiuiuouuuoeioaouaieiuoaooioaeeeeaoeaieeoeoeoaoueiuieeeaoeieeeeiiaiaaiiueooaiaeoioeiiuuiueaiioaeieeeiuiiuiueueoeaoeooeeeeaoeueuuueauoeeaioaioauoeuiaaoeouiaeuaouaeoaueoieiaieeieoiaieeiuoaiiouaaiuoeiieeeoaiuuuaoeiiaoaauaoaueuuoeuuiioaeaoooieiuaiueeoeooooueieaaieeiuoaeuaiaaiaueueeooauaaoaiouuooiiuaiaieuaouaoauueaiuouooooauuiuoioaoiuaaoouuuuaiiaaaieiuiaooueiauooaeoiueuieoiuauoieeueaueieuueiuoioeaoueeieouiueeieoeiuaouoooiiuoauaoiaeoaaoaiooooiuoueaeeoieaeuiuieuuuuouiiiaeoieeeaaeauaeueueueoeauueuaoiueauuuouuieuiuiaauaeaaiouaeuauoeeuooeaooouiaueueiouuuaeaieuiuaaoouuioaueueaeuiauaiauaeieuuieioueueueaeaaueaouiuoieeoueaiieioaooioueeiouoeauuieouioooooeoioaeiieuoioaeoiaaeaaioioeeiaaeuoeiuoauueaioeuoeeoeioiuuaeaiueuoiaiuuoaeaouoaeauiooiaaiaiaiiuaiuoeieaouoeuiouuoaeoooiaaiaeuuueaooaieeuiiooaaaueaoeuaeeoeuooeaiiuiaiuaiiuoa')); // 1576

